### ISSUE TITLE
My old project

### ISSUE THREAD

**Issue by aianlinb** [xafero/SharpMC#1]
I did a project for Minecraft Server in C# last year, but discontinued for time reason.
I upload it to Github just now, wondering if my code could help a little bit.
https://github.com/aianlinb/MCServerSharp

This project has a low level of completion and is not yet functioning properly.

**Comment by xafero** [comment]
Your project needs work, too.

1) It is using System.Drawing.Common, which is not cross-platform anymore.
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only
--> Needs conversion to ImageSharp.

2) It is using PInvoke & AllowUnsafeBlocks for Kernel32 for example.
--> Needs extraction into Win32 class library, maybe find Linux and/or Mac equivalents.

3) It is not licensed clearly.
--> Needs explicit inclusion of a LICENSE file for MIT, preferably.

**Comment by aianlinb** [comment]
@xafero Done https://github.com/aianlinb/MCServerSharp/commit/5928cb8179841e2f2de3bf5ae8ef88d75fca8cb1

By the way, I just thought maybe it has part of the code that can provide reference or help, no plans to keep working on it.

**Comment by xafero** [comment]
@aianlinb Thanks
